name: CI/CD Spring Web App Gabo

on: 
  push:
    branch: [main]

jobs: 
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout out code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Maven Dependences
        run: mvn install

      - name: Run test & generate Jar package
        run: mvn --batch-mode verify 

      - name: Login to docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          fie: Dockerfile
          push: true
          tags: gabrielibujes712/spring-bmi-calc:latest